"""稳定业务常量。

这里不放动态业务逻辑，只放跨 Agent、Workflow、Service 共享的领域枚举。
集中管理可以减少“资源类型”等字符串在项目里散落。
"""

RESOURCE_TYPE_LECTURE = "讲解文档"
RESOURCE_TYPE_EXERCISE = "练习题"
RESOURCE_TYPE_MINDMAP = "思维导图"
RESOURCE_TYPE_READING = "拓展阅读"
RESOURCE_TYPE_CODE = "代码案例"
RESOURCE_TYPE_KG = "知识图谱"

RESOURCE_TYPES = (
    RESOURCE_TYPE_LECTURE,
    RESOURCE_TYPE_EXERCISE,
    RESOURCE_TYPE_MINDMAP,
    RESOURCE_TYPE_READING,
    RESOURCE_TYPE_CODE,
    RESOURCE_TYPE_KG,
)

RESOURCE_TYPE_SET = set(RESOURCE_TYPES)

# 智能生成资源时的最低覆盖面，避免只生成单一文本资源。
DEFAULT_SMART_RESOURCE_TYPES = (
    RESOURCE_TYPE_LECTURE,
    RESOURCE_TYPE_EXERCISE,
    RESOURCE_TYPE_MINDMAP,
    RESOURCE_TYPE_READING,
    RESOURCE_TYPE_CODE,
    RESOURCE_TYPE_KG,
)
